### ISSUE TITLE
HoYoLab APIのセッションが切れるとアプリ起動時にコケる

### ISSUE THREAD

**Issue by Misaki0331** [Misaki0331/Genshin-Checker#4]
表題の通り。
時間があれば直す

**Comment by Misaki0331** [comment]
再認証してもログイン切れになってる。
`code:-100 - ログイン情報失効。再ログインしてください'`
ユーザーデータの削除してもダメっぽい
HeadersのDs内のsaltが悪さしてるかも。

**Comment by Misaki0331** [comment]
saltでほぼ確定かも
現状：別のアカウントで認証しようとしたら-100エラーが返ってきてる。
別アカウントでログインしたらもれなく別アカウントのログインの認証で全部コケるようになった。
過去にログインした物に関してはまだ問題はないっぽい？
`Error code:-100 - Login expired. Please log in again.`
`Error code:-100 - Unknown error`
この2つが返ってくるようになったかも

saltがまだログインデータがv2に対応してないとかかも？

**Comment by Misaki0331** [comment]
他のAPIでは実行できているのでsaltの問題ではなさそうかも？

**Comment by Misaki0331** [comment]
新規ログインの場合クッキーのログイントークンが全てv2しか返さないようになっていたっぽい。
``account_id_v2=123456789; ltmid_v2=*************;``
v1のクッキーを使って認証しているので多分新規ログインでは無理そう。

**Comment by donokoanoko** [comment]
必要かは分かりませんが、思ったよりめんどくさそうな状況なので一応送っておきますね。
このバグがPCa(Win11)のユーザaで起きたときに

- PCaで新たにユーザbを作成しGenshin-Checkerを初めて起動
- 別のPCb(Win10)にて、ユーザaと同じマイクロソフトアカウントでGenshin-Checkerを初めて起動

どちらでも同様のバグが発生しました。

**Comment by Misaki0331** [comment]
恐らくですが、11月以降に新しくログイン、あるいは再ログインにより連携したものに関しては仕様変更により全て正常に連携できなくなっている可能性が高いかもです。
逆に既に11月以前にログイン連携している場合は通常通り使用できる可能性が高いです。
現状HoYoLabを解析しているコミュニティで情報を模索していますが、見つかり次第追記します。

**Comment by Misaki0331** [comment]
あっ原因分かったかも
Cookieが悪さしてました。
HoYoLabのAPIでは`cookie_token_v2`, `ltoken_v2`が含まれていない事からエラーが発生したっぽい

**Comment by Misaki0331** [comment]
今の挙動：javascriptを通して現在のページのcookieを取得
戦績のページだけでは含まれていないデータが存在した為ログインができない事が今回の現象の原因

修正すべき点 : webview2本体からcookieを直接取得する
何も仕様変更じゃなかったみたいです。

**Comment by Misaki0331** [comment]
修正完了 
https://github.com/Misaki0331/Genshin-Checker/commit/8a148dec587712da5afa1de00dc459fb25ba92d5

**Comment by Misaki0331** [comment]
修正版をリリース https://github.com/Misaki0331/Genshin-Checker/releases/tag/0.5.0
